---
title: 崩溃笔记——彻底消除多线程操作数组崩溃
date: 2019-04-19 21:22:21
tags:
- 多线程
categories:
- 崩溃控制
---

## 前言
它就像个磨人的小妖精，和你不期而遇在各个灰度版本。异步操作数组，很容易导致崩溃，版本迭代过程中，开发中常常容易忽略，测试周期并发量不够，一般较难发现，下面我们来讨论下异步操作导致的问题和预防措施。

## 一、ConcurrentModificationException异常
1. ConcurrentModificationException出现的原因
看下ArrayList的源码，我们可以知道，有个校验的地方会抛出这个异常。
```
final void checkForComodification() {
    if (ArrayList.this.modCount != this.expectedModCount) {
        throw new ConcurrentModificationException();
    }
}
```
modCount：表示对数组的修改次数，在执行add和remove之后值会+1
expectedModCount：表示对数组修改次数的期望值，初始值和modCount一致
也就是说，在对数组执行操作前，会执行这个校验，如果期望修改次数和当前修改次数不一致，则会抛出这个异常。
下面用一个同步操作的例子，简单说明一下：


<!-- more -->


```
val list = mutableListOf<Int>()
list.add(1)
list.add(2)
list.add(3)
list.add(4)
list.add(5)

val iterator = list.iterator()
while (iterator.hasNext()) {
    val next = iterator.next()
    if (next == 2)
        iterator.remove()
}
System.out.println("$list")

list.forEach {
    if (it == 3)
        list.remove(it)
}
```
同样是使用迭代器遍历（注意，forEach也是使用迭代器），哪里会有问题呢？扒下源码看看。
原来，第一种方法迭代器remove会同步expectedModCount
```
try {
    ArrayList.this.remove(this.lastRet);
    this.cursor = this.lastRet;
    this.lastRet = -1;
    this.expectedModCount = ArrayList.this.modCount;
} catch (IndexOutOfBoundsException var2) {
    throw new ConcurrentModificationException();
}
```
第二种使用list的remove方法，只会对modCount+1，所以导致迭代器再下一次迭代的时候校验失败，抛出异常。

同步操作数组异常在开发中并不常见，且容易发现和解决，本文就不继续展开，有兴趣的朋友可以继续研究，下面着重看异步操作导致的问题。

2. 异步操作数组导致ConcurrentModificationException异常
先看一个例子：
```
val list = mutableListOf<Int>()
for (i in 1..10000) {
    list.add(i)
}

Thread {
    list.forEach {
        System.out.println(it)
    }
}.start()

Thread {
    list.remove(1)
}.start()
```
和同步的例子类似，只要你在遍历的时候，遇到修改，那么，你同样会遇到这个异常。在版本迭代维护中，这种异常是很常见的，甚至你只加了一点“简单”的代码就可能造成这个问题。
解决方案：
- 在大多数业务场景中，全局数组的操作都可以同步操作就满足需求，如果异步操作，可认为是bug，改为同步；
- 如果一定要异常处理，可以使用CopyOnWriteArrayList或者加锁，这种场景当然开销就更大；

CopyOnWriteArrayList在remove的时候会把数组先copy，再对新数组操作，以免影响原数组的读操作，以此来实现异步遍历和删除，CopyOnWriteArrayList虽然能解决一部分问题，仍有一些问题无法解决，即是下一小结的内容。

## 二、ArrayIndexOutOfBoundsException异常
数组越界也是常见的崩溃，下面分别列举两种情况下的崩溃和解决方法。
1. 同步操作数组越界
```
val list = mutableListOf<Int>()
for (i in 1..10000) {
    list.add(i)
}
list[10000]
```
比较简单，同步数组越界一般出现的比较少，也容易发现，同样也不做过多分析。
解决方案：通过下标索引访问时，先判断数组大小，养成良好的代码习惯

2. 异步操作数组越界
```
val list = mutableListOf<Int>()
for (i in 1..10000) {
    list.add(i)
}

Thread {
    for (i in 0..9999) {
        if (i < list.size) {
            list[i]
        }
    }
}.start()

Thread {
    list.clear()
}.start()
```
那么我已经养成良好的代码习惯了，遍历的时候，我每次都判断数组大小，再访问该数组，我是否已经安全了？
很遗憾，如果有其他线程正在删除同个数组，那你还是有可能出现这个崩溃。因为if条件此时是一个原子操作，而反问数组又是另外一个操作，那么其他线程则可能在你这两个操作之间删除了数据，那么就数组越界crash了。
那么如果换成线程安全的数组Vector呢？同样是不行的，道理同上。
那么如果换成CopyOnWriteArrayList呢？同样也是解决不了问题的，道理同上，CopyOnWriteArrayList甚至get方法也没有锁。
解决方案：
- 在遍历的方法块也加锁，这种方法如果经常迭代会导致难以维护，牵一发而动全身，如果处理不当性能影响较大。
- 尝试在同个线程处理这种通过索引遍历的方式和删除操作，甚至尽量所有操作同步处理。
- 在线程尽量对局部数组操作，操作完成后合并到全局数组。合并的过程最好和其他操作同步，或者其他方法，避免出现类似问题。

## 写在最后
总结归纳了一下多线程操作数组容易出现的问题和一些解决方案，后续如果发现其他问题或有新的思路，再继续补充完善，如有纰漏或其他见解，请大家评论或和我联系。

### 参考文献
1. [Java ConcurrentModificationException异常原因和解决方法](https://www.cnblogs.com/dolphin0520/p/3933551.html)
